# Generated by Django 4.1.5 on 2023-01-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cold', models.CharField(max_length=9)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=9)),
                ('peso', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('bairro', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=9)),
                ('arquivo', models.FileField(upload_to='arquivo')),
            ],
        ),
    ]
