# Generated by Django 4.1.5 on 2023-01-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoas',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='arquivo',
        ),
    ]
